[package]
authors = ["Marcel Math√© <m.mathe@gmx.net>"]
edition = "2018"
name = "day09"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
